### ISSUE TITLE
请问是否有发票查验数据接口？

### ISSUE THREAD

**Issue by ltt1987** [alcoholwang/e-invoicing#1]
我们想实现，根据发票代码等信息，对发票进行核验并获取发票的基本信息，请问您有解决的思路吗？

**Comment by alcoholwang** [comment]
目前比较全的是，国家税务总局全国增值税发票查验平台，https://inv-veri.chinatax.gov.cn/

不过还没找到相关API

**Comment by ltt1987** [comment]
谢谢！

**Comment by nishishanaoxing** [comment]
您好，想问一下您现在解决了没有，我们也想实现扫描发票信息，然后通过接口自动查询真伪，现在已知的有用友乐税阿里腾讯云等付费接口，现在就是公司不想付费，国税网查还实现不了大批量发票验证，想自己研发，目前就是不知道怎么对接这个接口，要找谁

**Comment by ltt1987** [comment]
> 您好，想问一下您现在解决了没有，我们也想实现扫描发票信息，然后通过接口自动查询真伪，现在已知的有用友乐税阿里腾讯云等付费接口，现在就是公司不想付费，国税网查还实现不了大批量发票验证，想自己研发，目前就是不知道怎么对接这个接口，要找谁

OCR与发票查验均需要付费，暂时没有免费方案。
